const ImageList = [
    {
      id: 1,
      src: "./image/home-program-1.jpg",
      alt: "hmprg1",
      title: "Resim 1",
      description: "Bu resim programın başlangıç görüntüsünü göstermektedir.",
    },
    {
      id: 2,
      src: "./image/home-program-2.jpg",
      alt: "hmprg2",
      title: "Resim 2",
      description: "Bu resim programın ikinci bölümünü göstermektedir.",
    },
    {
      id: 3,
      src: "./image/home-program-3.jpg",
      alt: "hmprg3",
      title: "Resim 3",
      description: "Bu resim programın üçüncü bölümünü göstermektedir.",
    },
    {
      id: 4,
      src: "./image/home-program-4.jpg",
      alt: "hmprg4",
      title: "Resim 4",
      description: "Bu resim programın dördüncü bölümünü göstermektedir.",
    },
    {
      id: 5,
      src: "./image/home-program-5.jpg",
      alt: "hmprg5",
      title: "Resim 5",
      description: "Bu resim programın beşinci bölümünü göstermektedir.",
    },
    {
      id: 6,
      src: "./image/1.jpg",
      alt: "hmprg6",
      title: "Resim 6",
      description: "Bu resim programın altıncı bölümünü göstermektedir.",
    },
    {
      id: 7,
      src: "./image/1.png",
      alt: "hmprg7",
      title: "Resim 7",
      description: "Bu resim programın yedinci bölümünü göstermektedir.",
    },
    {
      id: 8,
      src: "./image/2.jpg",
      alt: "hmprg8",
      title: "Resim 8",
      description: "Bu resim programın sekizinci bölümünü göstermektedir.",
    },
    {
      id: 9,
      src: "./image/2.png",
      alt: "hmprg9",
      title: "Resim 9",
      description: "Bu resim programın dokuzuncu bölümünü göstermektedir.",
    },
    {
      id: 10,
      src: "./image/4.jpg",
      alt: "hmprg10",
      title: "Resim 10",
      description: "Bu resim programın onuncu bölümünü göstermektedir.",
    },
    {
      id: 11,
      src: "./image/5.jpg",
      alt: "hmprg11",
      title: "Resim 11",
      description: "Bu resim programın onbirinci bölümünü göstermektedir.",
    },
    {
      id: 12,
      src: "./image/6.jpg",
      alt: "hmprg12",
      title: "Resim 12",
      description: "Bu resim programın onikinci bölümünü göstermektedir.",
    },
    {
      id: 13,
      src: "./image/7.jpg",
      alt: "hmprg13",
      title: "Resim 13",
      description: "Bu resim programın onüçüncü bölümünü göstermektedir.",
    },
    {
      id: 14,
      src: "./image/details-1.jpg",
      alt: "hmprg14",
      title: "Resim 14",
      description: "Bu resim programın ondördüncü bölümünü göstermektedir.",
    },
    {
      id: 15,
      src: "./image/details-2.jpg",
      alt: "hmprg15",
      title: "Resim 15",
      description: "Bu resim programın onbeşinci bölümünü göstermektedir.",
    },
    {
      id: 16,
      src: "./image/hero-3.jpg",
      alt: "hmprg16",
      title: "Resim 16",
      description: "Bu resim programın onaltıncı bölümünü göstermektedir.",
    },
  ];
  
  export default ImageList;
  